### ISSUE TITLE
New Design Layout Proposal

### ISSUE THREAD

**Issue by davidb2002** [EugeneKay/subsonic#14]
I've been discussing this with the users in the forum, and there appears to be some support for a redesign.

http://forum.subsonic.org/forum/viewtopic.php?f=3&t=15126

I know this isn't an official repository, but what are the chances of allowing modification of the code to fit a new design?

**Comment by rykerwilliams** [comment]
If you want a nicer front end, have a look at Jamstash,
https://github.com/tsquillario/Jamstash. (IMO) It already implements the
nicer features of your mockup.

**Comment by ainola** [comment]
@davidb2002, your mockup is absolutely stunning - I think it should hit the main subsonic repos with something of that calibre, though.

**Comment by EugeneKay** [comment]
The chances are exactly nil, sorry! This repo is maintained with minimal changes relative to upstream, so I would not accept anything like a visual overhaul.

I do agree that the mockup you've made looks nicer, but it's outside of scope for this repo. I would suggest trying to reach Sindre directly about providing alternative theme support for 6.0.
