### ISSUE TITLE
Is it possible to add feature to share media from own domain name, not from subsonic server?

### ISSUE THREAD

**Issue by Scorry** [EugeneKay/subsonic#18]
Hello, @EugeneKay !

All work as expected, but subsonic part of address media sharing seems hardcoded.
Is it possible to add feature to share media from own domain name, not from subsonic server?

Thank you.

**Comment by EugeneKay** [comment]
Hi @Scorry,

You don't need to change anything in the Subsonic application to enable this, it's all handled by your WAR application server. Reference this post for how to do it under Tomcat: http://stackoverflow.com/questions/5328518/deploying-my-application-at-the-root-in-tomcat
