### ISSUE TITLE
Some artifacts missing from Central Repository?

### ISSUE THREAD

**Issue by Lawrence5** [EugeneKay/subsonic#25]
First time using Maven. I synced Eugene'e repository and tried to follow the instructions in INSTALL.md to build Subsonic 5.3 (KORG). Maven fails with message that maven-dependency-plugin-2.2.jar is not a valid jar. I searched the Central Repository at maven.org and indeed there is no such artifact as maven-dependency-plug. Not knowing what else to do, I commented out all references to maven-dependency-plugin in the pom.xml. Everything built perfectly. I deployed the WAR and it runs fine.

What is maven-dependency-plugin supposed to do?

Thanks Eugene for making it easy for me to run Subsonic my way. I appreciate your effort.

Lawrence

**Comment by EugeneKay** [comment]
This is an error outside of the Subsonic build process(though that would be something to file against upstream anyway). The file referenced is downloaded by Maven as a dependency, and stored in ~/.m2. You should be able to remove this directory and re-run mvn. It will re-download everything it needs on the first run.
