### ISSUE TITLE
Sonos Integration

### ISSUE THREAD

**Issue by oneguynick** [EugeneKay/subsonic#26]
Looks like Sonos integration broke with the recent rev's of Sonos firmware and Subsonic. I see the API is still there, but it does not function with Sonos controllers anymore.

**Comment by EugeneKay** [comment]
Per [CONTRIBUTING](https://github.com/EugeneKay/subsonic/blob/release/CONTRIBUTING.md), please submit bug reports to the [upstream project](http://sourceforge.net/p/subsonic/bugs/)

**Comment by stevenroose** [comment]
@oneguynick Did you submit a bug upstream? Did you get it working?

I'm planning to do it next time I visit home since I temporarily lost access to my server.
