### ISSUE TITLE
The /stream endpoint has no auth option

### ISSUE THREAD

**Issue by migglu** [EugeneKay/subsonic#27]
Hello, 
My problem is I'm trying to expose subsonic to the public network and I noticed that the /stream endpoint has no authorization options, meaning any wrongdoer can brute force the id of a stream and force my server to do unnecessary transcoding. Maybe this is a wanted behaviour so you can stream to an external player, but an option to force an authentication would be great.

**Comment by EugeneKay** [comment]
Per [CONTRIBUTING.md[(https://github.com/EugeneKay/subsonic/blob/release/CONTRIBUTING.md), bug reports and feature requests should be directed to the upstream [Subsonic Project](http://www.subsonic.org/).
