### ISSUE TITLE
Clicking "Add" for a song also adds all subsequent songs

### ISSUE THREAD

**Issue by jolny** [EugeneKay/subsonic#28]
As the topic says, when I click Add for a single song, it adds all subsequent songs in that list. I've verified that it happens in albums and those "Top Songs" lists from Last.fm.

**Comment by EugeneKay** [comment]
Per [CONTRIBUTING.md](https://github.com/EugeneKay/subsonic/blob/release/CONTRIBUTING.md), bug reports and feature requests should be directed to the upstream [Subsonic Project](http://www.subsonic.org/).
