### ISSUE TITLE
[Feature Request] HTML5 Player

### ISSUE THREAD

**Issue by lmnotran** [EugeneKay/subsonic#29]
Hi,

Would it be possible to implement a HTML5 player instead of the flash player?

Mason

**Comment by euank** [comment]
This repository is not the official upstream subsonic repo and does not typically make changes other than those related to building. See the [about](https://github.com/EugeneKay/subsonic#about) section of the readme.

[This request](http://sourceforge.net/p/subsonic/feature-requests/15/) also already exists upstream in the sourceforge subsonic project, and there appears to be an open source third party player already available named [JamStash](https://github.com/tsquillario/Jamstash).

**Comment by EugeneKay** [comment]
Per [CONTRIBUTING.md](https://github.com/EugeneKay/subsonic/blob/release/CONTRIBUTING.md), bug reports and feature requests should be directed to the upstream [Subsonic Project](http://www.subsonic.org/).
