### ISSUE TITLE
Installation guide outdated

### ISSUE THREAD

**Issue by WarlaxZ** [EugeneKay/subsonic#30]
So the readme suggest that we just drop the war file in as a replacement into tomcat, however the current install of subsonic uses jetty and has no war file to replace anywhere :/

**Comment by WarlaxZ** [comment]
for anyone else reading this, I resolved the issue by rm -rf jetty/<number>/* and then unzipping the tar file into this folder

**Comment by fr500** [comment]
which tar?

**Comment by uzantonomon** [comment]
I guess he meant the .war.

**Comment by EugeneKay** [comment]
I'm not familiar with the current version of the Subsonic Windows Installer. I will remove the reference to Tomcat. I do not use the Windows build. If you submit a Pull Request with a documentation update or more information, I would be glad to include it. Thanks for your report!

**Comment by EugeneKay** [comment]
The current README does not reference the drop-in replacement to the Subsonic installer(it did previously), so no change is needed. You would need to install a Tomcat server(they provide installers for most major OSes), and then install the .WAR into the webapps/ dir. I can improve the documentation if this is not clear.
