### ISSUE TITLE
Subsonic 6.0.beta1 release

### ISSUE THREAD

**Issue by Micdu70** [EugeneKay/subsonic#31]
Hello, I would like to know if you (EugeneKay) are working on the new beta version (6.0) of subsonic. 

And thanks for making "Libre" Subsonic to all. =)

**Comment by EugeneKay** [comment]
SourceForge SVN services appear to be down currently. I'll try to get a build out sometime this weekend, but Beta builds are not worth my trouble.

**Comment by EugeneKay** [comment]
A new build is out: https://github.com/EugeneKay/subsonic/releases/tag/v6.0-beta1-kang

There were merge conflicts due to the upstream UI revamp. I have tested what I could see and it looks good, but bear in mind that this is a Beta.

**Comment by Micdu70** [comment]
Great! Thanks! ;-)
