### ISSUE TITLE
[6.0 beta 1 kang] Unable to play music from the web interface

### ISSUE THREAD

**Issue by spijet** [EugeneKay/subsonic#34]
Nothing happens when I'm trying to play anything from the web interface when using latest kang WAR.
That's what I get in Firefox JS console:
`GET 
http://31.47.x.x:8080/subsonic/dwr/engine.js [HTTP/1.1 500 Internal Server Error 13мс]`
`GET 
http://31.47.x.x:8080/subsonic/dwr/interface/multiService.js [HTTP/1.1 500 Internal Server Error 11мс]`
`GET 
http://31.47.x.x:8080/subsonic/dwr/engine.js [HTTP/1.1 500 Internal Server Error 21мс]`
`GET 
http://31.47.x.x:8080/subsonic/dwr/interface/multiService.js [HTTP/1.1 500 Internal Server Error 17мс]`
<clicking the play button>
`18:02:25.996 ReferenceError: playQueueService is not defined1 playQueue.view:727:8`
I checked Tomcat webapps dir and found that there's no subsonic/dwr directory.

**Comment by EugeneKay** [comment]
Bug reports should be submitted to the Upstream project. See [CONTRIBUTING](https://github.com/EugeneKay/subsonic/blob/release/CONTRIBUTING.md) for more details.
