### ISSUE TITLE
How to customize HTML?

### ISSUE THREAD

**Issue by MaxPleaner** [EugeneKay/subsonic#35]
Hi, I'm asking this question in hopes that I can change the HTML structure just a little bit. I'm not familiar with this Java framework, so I don't where I'd find the HTML file I need to change.

Specifically, I'm looking for "index.view", so that I can make some of the letters (A-Z) smaller. 

I suppose this could be considered a documentation request, because the program itself is running swimmingly.

**Comment by EugeneKay** [comment]
https://github.com/EugeneKay/subsonic/tree/release/subsonic-main/src/main/webapp/WEB-INF/jsp is what you're looking for. I won't accept any patches for visual changes per CONTRIBUTING.md, but you are of course welcome to do whatever you like for yourself.

**Comment by EugeneKay** [comment]
If you would like a more maintainable solution you can probably make the changes you need client-side with an extension like StyleBot or Stylish purely in CSS. This will save you a lot of effort with recompiling and keeping-up with the current version.
