### ISSUE TITLE
How to build Windows executable?

### ISSUE THREAD

**Issue by rafspeik** [EugeneKay/subsonic#37]
How can I build a Windows exe file from this source? Is it even possible? I noticed that mach5's 'supersonic' has an exe in the download section but it's very outdated.

**Comment by EugeneKay** [comment]
I don't know the process to build a Windows target from this repo, sorry. I believe that it would be very similar to the Debian instructions(see INSTALL.md), but using the subsonic-installer-windows target(see pom.xml) instead. I do not have the build environment nor the desire to make this work myself, but I would very much welcome documentation contributions if you figure it out.

I provide a WAR which will run under a [Tomcat application server](http://tomcat.apache.org/) on any platform, including Windows. I suggest trying that out first.

**Comment by kornkid5622** [comment]
You can build the windows executable using Apache Maven, in windows you would open cmd prompt to the folder where you extracted the build and then type "mvn package -P full" to build the full package (this will provide windows executable as well as installers for other platforms)

for those who have no idea what i'm talking about i've compiled the executable and uplaoded it here: http://www.mediafire.com/download/98qp55oe5pub031/subsonic-6.0.beta1-setup.exe

**Comment by muff1nman** [comment]
I have deleted a comment with a link to media fire. Please no external download links.
