### ISSUE TITLE
UTF-8  support

### ISSUE THREAD

**Issue by fr500** [EugeneKay/subsonic#38]
I know this fork doesn't diverge significantly from upstream, but I've been trying to fix UTF-8 filenames for a while, I have files that use special characters and for some reason those can't be played (01 - 01 - Tabú.m4a shows up as Tab��.m4a)

**Comment by EugeneKay** [comment]
I don't see a Pull Request attached to this Issue; did Github eat it?

The upstream project is now [on github](https://github.com/sindremehus/subsonic), and I will be rebasing this repo against it under #36. Your best bet is to submit a PR directly there, and it will get included in the rebase.
